apiVersion: v1
kind: Secret
metadata:
  name: porfolio-secrets
  namespace: default
type: Opaque
data:
  JWT_SECRET: anNvbi13ZWItdG9rZW4tc2VjcmV0by1tdXktbGFyZ28tYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnc=
  SESSION_SECRET: c2Vzc2lvbi1zZWNyZXQtbXV5LWxhcmdvLWFiY2RlZmdoaWprbG1ub3BxcnN0dXZ3eHl6MTIzNDU2Nzg5MA==
  API_KEY: YXBpLWtleS1kZW1vLW11eS1sYXJnby1hYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejEyMzQ1Njc4OTBhYmNkZWY=
